import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header from '@/components/header'
import axios from 'axios'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })
import {RiMapPin2Line} from 'react-icons/ri'
import { useState } from 'react'
export default function Home({category, latest}) {

  const [filterText, setFilterText] = useState('');
  const [data, setData] = useState(category);

  function formatDate(dateString) {
    const options = { year: 'numeric', month: 'short', day: 'numeric' };
    const date = new Date(dateString);
    const locale = 'tr-TR';
  
    return date.toLocaleDateString(locale, options);
  }

  const filterData = (filterText) => {
    const filteredData = data.filter((item) =>
    item.city_name
      .toLocaleLowerCase('tr-TR') // Türkçe harf duyarlılığını yok say
      .includes(filterText.toLocaleLowerCase('tr-TR'))
  );
    return filteredData;
  };

  const filteredData = filterData(filterText);
  

  return (
    <>
      <Head>
        <title>İş İlanları</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
       <Header />
       <div className='slider'>
        <div className='container'>
          <div className='row align-items-center'>
            <div className='col-lg-6 col-12'>
              <div className='text'>
                <strong>İlgi alanınıza ve yeteneklerinize uygun bir iş bulun.</strong>
                <span>Yeteneklerinizi objektif bir şekilde değerlendirmek, iş arayışında çok önemlidir. Hangi becerilere sahip olduğunuzu ve bu becerileri nasıl kullanabileceğinizi düşünün. Kendinize şu soruları sorarak başlayabilirsiniz: "Hangi konularda iyiyim? Hangi becerilerim sıkça övgü alıyor?" Yeteneklerinizi tanımlamak, hangi işlerin size uygun olduğunu anlamanıza yardımcı olur.</span>
                <span></span>
              </div>
            </div>
            <div className='col-lg-6 col-12'>
              <img src='./slider.png' className='w-100' />
            </div>
          </div>
        </div>
       </div>
       <div className='citys'>
        <div className='container'>
          <div className='heading'>
            Tüm Şehirler
            <div>
            <input
            type="text"
            placeholder="Şehir ara..."
            onChange={(e) => {
              const filteredData = filterData(e.target.value);
              setFilterText(e.target.value)
        
            }}
          />
            </div>
          </div>
          <div className='list'>
            <div className='row'>
            {filteredData.length > 0 ? (
                filteredData.map((item) => (
                  <div className='col-lg-3 col-6' key={item.city_id}>
                    <Link href={`/is-ilanlari/${item.city_slug}`}>
                      {item.city_name}
                    </Link>
                  </div>
                ))
              ) : (
                <div className='col-12'>
                  <div className='alert alert-warning text-center'>Sonuç Bulunamadı</div>
                </div>
              )}
            </div>
          </div>
        </div>
       </div>
       <div className='latest'>
        <div className='container'>
          <div className='heading'>
            Son Eklenen İş İlanları
          </div>
          <div className='list'>
            <div className='row'>
              {latest.jobs.map((item) => (
              <div className='col-lg-4 col-12'>
                <Link key={item.job_id} href={`/detay/${item.job_slug}`} className='item'>
                  <div className='title'>
                  {item.job_title}
                  </div>
                  <div className='status'>
                    Tam Zamanlı
                  </div>
                  <div className='company'>
                    <div className='first'>
                      <div className='title'>
                        {item.job_company}
                      </div>
                      <div className='location'>
                      <RiMapPin2Line /> {item.city_name}, {item.district_name}
                      </div>
                    </div>
                    <div className='last'>
                      {formatDate(item.job_date)}
                    </div>
                  </div>
                </Link>
              </div>
              ))}
            </div>
          </div>
        </div>
       </div>
      </main>
    </>
  )
}

export async function getServerSideProps({ params }) {

  try {
      const apiUrl = process.env.API_URL;
      const response = await axios.get(`${apiUrl}city?all=1`);
      const latest_response = await axios.get(`${apiUrl}jobs.php?order=DESC&limit=9`);
      const category = response.data;
      const latest = latest_response.data;

      return {
          props: {
              category,
              latest
          },
      };
  } catch (error) {
      return {
          props: {
              category: null,
              latest: null
          },
      };
  }
}
